### ISSUE TITLE
Show VCS branch name in build notification

### ISSUE THREAD

**Issue by g7r** [PeteGoo/tcSlackBuildNotifier#126] opened 2016-10-26 15:34 UTC

**Comment by pointerxr** [comment] 2016-10-26 18:08
The VCS branch name is only showing for branches other than default and this is working as intended. 

I'm gonna close this therefore as I can't find any details in the description.

**Closed by pointerxr** 2016-10-26 18:08 UTC
Labels: enhancement

**Comment by g7r** [comment] 2016-10-26 18:12
OK
